apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  storage:
    size: 1Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-secret
  backup:
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://k3s-barman/keycloak-db
      endpointURL: https://${S3_BACKUP_SERVER}:9091
      s3Credentials:
        accessKeyId:
          name: keycloak-db-minio-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: keycloak-db-minio-secret
          key: AWS_SECRET_ACCESS_KEY
    retentionPolicy: "30d"
