apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: tempo-distributed
    repo: https://grafana.github.io/helm-charts
    version: 1.9.9
    releaseName: "tempo"
    namespace: tempo
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml