apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluentd-externalsecret
  namespace: fluent
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fluent-secrets
  data:
  - secretKey: fluentd-shared-key
    remoteRef:
      key: logging/fluentd
      property: shared_key
  - secretKey: es-username
    remoteRef:
      key: logging/es-fluentd
      property: user
  - secretKey: es-password
    remoteRef:
      key: logging/es-fluentd
      property: password     
