---

# Get list of packages installed
- name: Get list of packages
  package_facts:
    manager: auto

- name: Check whether snap is package is installed
  debug:
    msg: "snapd found"
  when: "'snapd' in ansible_facts.packages"

- name: Remove snap package
  include_tasks: remove_snap.yaml
  when: "'snapd' in ansible_facts.packages"

- name: Execute RaspberryPi specific setup tasks
  include_tasks: raspberrypi_tasks.yml
  when: "'raspberrypi' in group_names"

- name: Blacklist storage devices in multipath configuration
  include_tasks: multipath_blacklist.yml
