###########################
# linkerd-jaeger subchart
###########################

linkerd-jaeger:
  # Disable OTel collector installation
  collector:
    enabled: false
  # Disable Jaeger installation
  jaeger:
    enabled: false
  # Configure jaeger-injector to use tempo embedded OTel collector
  webhook:
    collectorSvcAddr: tracing-tempo-distributor.tracing:55678
    collectorSvcAccount: tempo
