---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-app
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cilium-app
  path: ./kubernetes/platform/coredns/app/overlays/prod
  prune: true
