---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cilium-app
  path: ./kubernetes/platform/coredns/app/overlays/prod
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: coredns
      namespace: kube-system
