---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/flux-operator/operator/overlays/prod
  prune: true
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator-instance
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-operator-app
  path: ./kubernetes/platform/flux-operator/instance/overlays/prod
  prune: true
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-operator-instance
  path: ./kubernetes/platform/flux-operator/tofu-controller/overlays/prod
  prune: true
  wait: true