# nginx application
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/nginx/app/overlays/prod
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ingress-nginx
      namespace: nginx
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
