---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafdrop-kafka-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kafdrop-kafka-secret
  data:
  - secretKey: username
    remoteRef:
      key: kafka/kafdrop
      property: user
  - secretKey: password
    remoteRef:
      key: kafka/kafdrop
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafdrop-kafka-propeties-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kafdrop-config
    template:
      engineVersion: v2
      data:
        kafka.properties: |
          security.protocol=SASL_PLAINTEXT
          sasl.mechanism=SCRAM-SHA-512
          sasl.jaas.config="org.apache.kafka.common.security.scram.ScramLoginModule required username='{{ .username | toString }}' password='{{ .password | toString }}';"
  data:
  - secretKey: username
    remoteRef:
      key: kafka/kafdrop
      property: user
  - secretKey: password
    remoteRef:
      key: kafka/kafdrop
      property: password