---
- name: Ensure haproxy package is installed
  ansible.builtin.package:
    name: 'haproxy'
    state: 'present'
    update_cache: true

- name: Copy haproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
    validate: haproxy -f %s -c -q
  notify: Restart haproxy

- name: Ensure haproxy is running and enabled
  ansible.builtin.service:
    name: "haproxy"
    state: started
    enabled: true
