apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.9.17
    releaseName: "external-secrets"
    namespace: external-secrets
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml