{{- $passwordValue := (randAlphaNum 16) | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: es-prometheus-user-file-realm
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ "prometheus" | b64enc }}
  password: {{ $passwordValue }}
  roles: {{ "prometheus_role" | b64enc }}