# longhorn helm values (ingress)

# Ingress Resource. Longhorn dashboard.
ingress:
  ## Enable creation of ingress resource
  enabled: true
  ## Add ingressClassName to the Ingress
  ingressClassName: nginx
 
  # ingress host
  host: longhorn.${CLUSTER_DOMAIN}

  ## Set this to true in order to enable TLS on the ingress record
  tls: true

  ## TLS Secret Name
  tlsSecret: longhorn-tls

  ## Default ingress path
  path: /

  ## Ingress annotations
  annotations:

    # Enable external authentication using Oauth2-proxy
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.${CLUSTER_DOMAIN}/oauth2/start?rd=https://$host$request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization

    # Enable cert-manager to create automatically the SSL certificate and store in Secret
    # Possible Cluster-Issuer values: 
    #   * 'letsencrypt-issuer' (valid TLS certificate using Letsencrypt) 
    #   * 'ca-issuer' (CA-signed certificate, not valid)
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    cert-manager.io/common-name: longhorn.${CLUSTER_DOMAIN}