apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ingress.yaml
  - grafana-env-externalsecret.yaml
  - grafana-externalsecret.yaml

# Generate dashboards config maps (one per dashboard)
configMapGenerator:
- name: dashboard-k3s-apiserver
  files:
  - dashboards/k3s-apiserver.json
- name: dashboard-k3s-controllmanager
  files:
  - dashboards/k3s-controllermanager-dashboard.json
- name: dashboard-k3s-etcd
  files:
  - dashboards/k3s-etcd.json
- name: dashboard-k3s-kubelet
  files:
  - dashboards/k3s-kubelet.json
- name: dashboard-k3s-scheduler
  files:
  - dashboards/k3s-scheduler-dashboard.json
- name: dashboard-longhorn
  files:
  - dashboards/longhorn-dashboard.json
- name: dashboard-nginx
  files:
  - dashboards/nginx.json
- name: dashboard-minio
  files:
  - dashboards/minio-dashboard.json
- name: dashboard-velero
  files:
  - dashboards/velero-dashboard.json
- name: dashboard-elasticsearch
  files:
  - dashboards/elasticsearch.json
- name: dashboard-fluent-bit
  files:
  - dashboards/fluent-bit-dashboard.json
- name: dashboard-pi-cluster
  files:
  - dashboards/pi-cluster-dashboard.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"