apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    group: elasticsearch.k8s.elastic.co
    kind: Elasticsearch
    name: efk
  path: elasticsearch-patch.yaml
- target:
    group: kibana.k8s.elastic.co
    kind: Kibana
    name: efk
  path: kibana-patch.yaml