apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
  - ../../base

components:
  - ../../components/security
  - ../../components/superuser
  - ../../components/external-listener
  - ../../components/monitor