---

- name: Ensure htpasswd utility is installed
  ansible.builtin.package:
    name: 'apache2-utils'
    state: 'present'
    update_cache: true
  become: true

- name: Htpasswd utility
  ansible.builtin.command:
    cmd: >-
      htpasswd -nb {{ ingress_basic_auth_user }} {{ ingress_basic_auth_passwd }}
  register: htpasswd
  changed_when: false

- name: Set htpasswd pair
  ansible.builtin.set_fact:
    ingress_auth_htpasswd_pair: "{{ htpasswd.stdout }}"


- name: Create/update ingress/basic_auth credentials
  ansible.builtin.uri:
    url: "https://{{ vault_dns }}:8200/v1/secret/data/ingress/basic_auth"
    method: POST
    headers:
      X-Vault-Token: "{{ token_data | community.hashi_vault.vault_login_token }}"
    body:
      data:
        htpasswd-pair: "{{ ingress_auth_htpasswd_pair }}"
    body_format: json
