---

# hashi_vault.vault_write module is not working
#
# - name: Create {{ secret_group.key }} credentials
#   community.hashi_vault.vault_write:
#     url: "https://{{ vault_dns }}:8200"
#     path: "secret/{{ secret_group.key }}/{{ secret.key }}"
#     data: "{{ secret.value }}"
#     auth_method: token
#     token: '{{ token_data | community.hashi_vault.vault_login_token }}'
#   loop: "{{ secret_group.value | dict2items }}"
#   loop_control:
#     loop_var: secret

# https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#create-update-secret
- name: "Create/update credentials: {{ secret_group.key }}"
  ansible.builtin.uri:
    url: "https://{{ vault_dns }}:8200/v1/secret/data/{{ secret_group.key }}/{{ secret.key }}"
    method: POST
    headers:
      X-Vault-Token: "{{ token_data | community.hashi_vault.vault_login_token }}"
    body:
      data: "{{ secret.value }}"
    body_format: json
  loop: "{{ secret_group.value | dict2items }}"
  loop_control:
    loop_var: secret
  no_log: true
