# external-dns helm values (base)

provider:
  name: rfc2136

env:
  - name: EXTERNAL_DNS_RFC2136_HOST
    value: "${EXTERNAL_DNS_SERVER}"
  - name: EXTERNAL_DNS_RFC2136_PORT
    value: "53"
  - name: EXTERNAL_DNS_RFC2136_ZONE
    value: ${CLUSTER_DOMAIN}
  - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
    value: "true"
  - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
    value: ddnskey
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
    value: hmac-sha512
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: external-dns-bind9-secret
        key: ddns-key

policy: sync
registry: txt
txtOwnerId: k8s
txtPrefix: external-dns-
sources: 
  - crd
  - ingress
  - istio-gateway
domainFilters: 
  - ${CLUSTER_DOMAIN}
logLevel: debug
serviceMonitor:
  enabled: true