apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

resources:
  - ns.yaml
  - minio-externalsecret.yaml
  - keycloak-env-externalsecret.yaml
  - keycloak-externalsecret.yaml
  - keycloak-db-externalsecret.yaml

# Generate keycloak config realm
configMapGenerator:
- name: keycloak-realm-configmap
  files:
  - picluster-realm.json  
