---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_DOMAIN: homelab.ricsanfre.com
  S3_BACKUP_SERVER: s3.ricsanfre.com
  EXTERNAL_DNS_SERVER: 10.0.0.11
  LB_POOL_MIN: 10.0.0.50
  LB_POOL_MAX: 10.0.0.99
  NGINX_LOAD_BALANCER_IP: 10.0.0.50
  FLUENTD_LOAD_BALANCER_IP: 10.0.0.51