apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: 21.3.1
    releaseName: "keycloak"
    namespace: keycloak
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml