apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.5.2
    releaseName: "loki"
    namespace: loki
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml