apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-externalsecret
  namespace: keycloak
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
  data:
    - secretKey: admin-password
      remoteRef:
        key: keycloak/admin
        property: password
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue
