apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elasticsearch-fluentd-externalsecret
  namespace: logging
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: es-fluentd-user-file-realm
    template:
      type: kubernetes.io/basic-auth
      data:
        username: |-
          {{ `{{ .username | toString }}` }}
        password: |-
          {{ `{{ .password | toString }}` }}
        roles: fluentd_role
  data:
  - secretKey: username
    remoteRef:
      key: logging/es-fluentd
      property: user
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
      metadataPolicy: None # ArgoCD sync issue
  - secretKey: password
    remoteRef:
      key: logging/es-fluentd
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
      metadataPolicy: None # ArgoCD sync issue