---
roles:
  - name: ricsanfre.security
    version: v1.0.0
  - name: ricsanfre.ntp
    version: v1.0.0
  - name: ricsanfre.firewall
    version: v1.0.0
  - name: ricsanfre.dnsmasq
    version: v1.0.4
  - name: ricsanfre.bind9
    version: v1.0.6
  - name: ricsanfre.storage
    version: v1.0.0
  - name: ricsanfre.iscsi_target
    version: v1.0.0
  - name: ricsanfre.iscsi_initiator
    version: v1.1.1
  - name: ricsanfre.k8s_cli
    version: v1.0.0
  - name: ricsanfre.fluentbit
    version: v1.0.5
  - name: ricsanfre.minio
    version: v1.1.12
  - name: ricsanfre.backup
    version: v1.1.3
  - name: ricsanfre.vault
    version: v1.0.4
  - name: geerlingguy.node_exporter
    version: 2.1.2
collections:
  - name: community.general
    version: 11.1.0
  - name: kubernetes.core
    version: 6.0.0
  - name: community.hashi_vault
    version: 7.0.0
  - name: ansible.posix
    version: 2.1.0
  - name: community.crypto
    version: 3.0.1
