---
roles:
  - name: ricsanfre.security
    version: v1.0.0
  - name: ricsanfre.ntp
    version: v1.0.0
  - name: ricsanfre.firewall
    version: v1.0.0
  - name: ricsanfre.dnsmasq
    version: v1.0.2
  - name: ricsanfre.storage
    version: v1.0.0
  - name: ricsanfre.iscsi_target
    version: v1.0.0
  - name: ricsanfre.iscsi_initiator
    version: v1.1.1
  - name: ricsanfre.k8s_cli
    version: v1.0.0
  - name: ricsanfre.fluentbit
    version: v1.0.4
  - name: ricsanfre.minio
    version: v1.1.4
  - name: ricsanfre.backup
    version: v1.1.3
  - name: ricsanfre.vault
    version: v1.0.4
collections:
  - name: community.general
    version: 8.5.0
  - name: kubernetes.core
    version: 3.0.1
  - name: community.hashi_vault
    version: 6.2.0
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.18.0
