---
- name: Shutdown Pi Cluster nodes
  hosts: picluster
  become: true
  gather_facts: false
  tasks:
    - name: Shutdown
      ansible.builtin.command: shutdown -h 1 min
      ignore_errors: true

- name: Shutdown Gateway node
  hosts: gateway
  become: true
  gather_facts: false
  tasks:
    - name: Shutdown
      ansible.builtin.command: shutdown -h 1 min
      ignore_errors: true
