
# Prometheus monitoring
serviceMonitor:
  enable: true
  release: monitoring

# Ingress configuration
ingress:
  host: linkerd.picluster.ricsanfre.com
  # configure cert-manager issuer
  certmanager:
    # tlsIssuer=letsecrypt to generate valid TLS certficiate using IONOS API
    # tlsIssuer=ca to generate a CA-signed certificate (not valid)
    tlsIssuer: letsencrypt
    # tlsIssuer: ca
  # Enabling nginx basic authorization, reusing global nginx basic auth secret
  basicAuth:
    enable: false
  # Enabling oauth2 through oauth2-proxy
  oauth2:
    enable: true
    proxy: https://oauth2-proxy.picluster.ricsanfre.com

########################
# linkerd-viz subchart
########################

linkerd-viz:
  # Skip namespace creation
  installNamespace: false
  # External Prometheus
  prometheusUrl: http://monitoring-prometheus.monitoring.svc.cluster.local:9090
  prometheus:
    enabled: false
  # External Grafana
  grafana:
    url: monitoring-grafana.monitoring.svc.cluster.local
  # Disabling DNS rebinding protection. Only needed with Traefik Ingress
  # dashboard:
  #   enforcedHostRegexp: .*
