apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.15.5
    releaseName: "cilium"
    namespace: kube-system
    valuesFile: ../../base/values.yaml
    includeCRDs: true
    additionalValuesFiles:
      - values.yaml
