apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: 7.5.4
    releaseName: "oauth2-proxy"
    namespace: oauth2-proxy
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml