# Site settings
title: Pi Kubernetes Cluster
email: admin@ricsanfre.com
description: >
  How to build a hybrid x86/ARM Kubernetes cluster at home, using Raspberry Pi and refurbished mini PCs, and automate its deployment and configuration applying IaC (infrastructure as a code) and GitOps methodologies with tools like Ansible and Argo CD.
lang: en-US

author:
  name: Ricardo Sanchez
  twitter: ricsanfre
twitter:
  username: ricsanfre
  card: summary
social:
  name: Ricardo Sanchez
  links:
    - https://twitter.com/ricsanfre
    - https://github.com/ricsanfre

# Timezone
timezone: Europe/Madrid

# Enable matoma analytics
matoma_analytics: true
matoma:
  url: web-analytics.ricsanfre.com
  site_id: 1

# giscus comments
giscus:
  repo: ricsanfre/pi-cluster
  repo_id: MDEwOlJlcG9zaXRvcnkzNzk5ODc5NzY=
  category: Announcements
  category_id: DIC_kwDOFqYoCM4CUyX7


baseurl: "" # the subpath of your site, e.g. /blog/
url: https://picluster.ricsanfre.com # the base hostname & protocol for your site
git_address: https://github.com/ricsanfre/pi-cluster
git_edit_address: https://github.com/ricsanfre/pi-cluster/blob/master

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: cyborg # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown

# Allow kramdown to parse inside html blocks (Generate toc)
kramdown:
  parse_block_html: true

highlighter: rouge

# Plugins (previously gems:)
plugins:
#  - jekyll-remote-theme
#  - jekyll-toc
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor


defaults:
- scope:
    path: ""
  values:
    image: /assets/img/pi-logo-reduced.png
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: news
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"
    toc: true
    comments: true
    last_modified_at: "29-01-2022"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
