apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: basic-auth-secret
    template:
      engineVersion: v2
      data: 
        users: |2
          {{ printf "{{ .htpasswdPair }}" }}
  data:
  - secretKey: htpasswdPair
    remoteRef:
      key: ingress/basic_auth
      property: htpasswd-pair
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
      metadataPolicy: None # ArgoCD sync issue
