---

- name: Run pre-configuration tasks
  include_tasks: pre_configuration.yml

- name: Get K3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0766'

- name: Install K3s
  command: "/tmp/k3s_install.sh agent"
  environment:
    K3S_TOKEN: "{{ k3s_token }}"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  changed_when: true
