---

- name: Ensure registration ip is defined
  ansible.builtin.set_fact:
    k3s_registration_ip: "{{ k3s_api_vip | default(hostvars[groups['k3s_master'][0]].ansible_host) }}"

- name: Create K3S configuration directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/rancher/k3s

- name: Generate k3s token file on all nodes
  ansible.builtin.copy:
    content: "{{ k3s_token }}"
    dest: "{{ k3s_token_file }}"
    mode: "0600"

- name: Copy kubelet configuration file
  ansible.builtin.copy:
    dest: "{{ k3s_config_directory }}/kubelet.config"
    content: "{{ k3s_kubelet_config }}"
    mode: "0644"

- name: Copy k3s configuration file
  ansible.builtin.template:
    src: "templates/config.yml.j2"
    dest: "{{ k3s_config_file }}"
    mode: "0644"

- name: Ensure containerd registries file exists
  ansible.builtin.template:
    src: "templates/registry.yml.j2"
    dest: "{{ k3s_registries_file }}"
    mode: "0600"
